package domain;
// Generated Sep 7, 2010 2:31:25 PM by Hibernate Tools 3.2.1.GA



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer id;
     private Producttype producttype;
     private String name;
     private float price;
     private String content;
     private String images;

    public Products() {
    }

    public Products(Producttype producttype, String name, float price, String content, String images) {
       this.producttype = producttype;
       this.name = name;
       this.price = price;
       this.content = content;
       this.images = images;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producttype getProducttype() {
        return this.producttype;
    }
    
    public void setProducttype(Producttype producttype) {
        this.producttype = producttype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }




}


