package domain;
// Generated Sep 7, 2010 2:31:25 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producttype generated by hbm2java
 */
public class Producttype  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set productses = new HashSet(0);

    public Producttype() {
    }

	
    public Producttype(int ID) {
        this.id = ID;
    }
    
    public Producttype(String name) {
        this.name = name;
    }
    public Producttype(String name, Set productses) {
       this.name = name;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


